export { default as User } from './User'
export { default as Train } from './Train'
export { default as Booking } from './Booking'
export { default as Payment } from './Payment'
export { default as Review } from './Review'
export { default as Notification } from './Notification'
export { default as Station } from './Station'
export type { IUser } from './User'
export type { ITrain, ISeat } from './Train'
export type { IBooking, IPassengerDetail } from './Booking'
export type { IPayment } from './Payment'
export type { IReview } from './Review'
export type { INotification } from './Notification'
export type { IStation } from './Station'
